language: python
sudo: false
python:
- '2.7'
script:
- echo h
deploy:
  provider: pypi
  user: Alex.F
  password:
    secure: RDUgZqvUqfvBaF6Iod2BSQJdu4U2pO78P4kdoJuERClf6+OX8nPPFSEmoqaI+0IH9yMoZ+uxAQMSrtnPGkVCUz7gjNEysRNcxY/3Xbupllsz9ydeHRDoPs2KwMZt0c4R6Q8VTsMfTGYpjlyYCNfHGeNQ78vU9UWmPkIU81ozeT4Zb12oVaWz4qS6QbXeUfp7ZPE36ukcwwd6qaNYdMXOwDyEBqhj9KqNZlAIaEBigJz8ziWWTXbkx1ihqS4Y0rT8JbFRpUTEXtiHOKavmEhfGMt+u39rGxP3kj0gjxTCe+mL3G8X/BEMRFGUg/klIPGSsyoUnMvmkEFH32C/9ilJpE1MpPLsUIdkJ21voRHdar3xS17+fbcYtPLDHpqoPJMZRnoZDb/Kwp3vUg4e/tkOYvP+Sa12dzNjssTeKUJdPjSMjGjrSbi1PIXdE9kSWeFwFK5F92UvwvUdO6PTmQuB8HMiwOalqiZdaUVIliQJ/fo/jU2fM2hehTX5oXchLROc+xLOiFRdfyPXnplGxfJ359mGR3txQmjh5yFI4AR3vGDyKs8/iQlpksfK/lZULuXybTF7WEdTGX5u9WImn4kDzVdKTEYKMRv1Lou6NfEdpC23fLn0gOAG+ovv0EFqKv5DjFX2/peKWoSu1a4NjhopochZlF2B/nOrslJnWEAgzzI=
  on:
    repo: gfreezy/Flask-Statsd
    tags: true
